version: 2

sources:
  - name: raw_data   # Logical name you choose for use in dbt code
    description: "Raw data sources for NYC taxi rides"
    database: terraform-project-485722
    database: copper-seeker-466202-f5  # GCP Project ID that owns the data
    schema: nytaxi  # BigQuery dataset name (like `staging`, `raw`, etc.)

    tables: 
      - name: green_tripdata  #Table name in BigQuery Dataset
      - name: yellow_tripdata
      - name: fhv_tripdata
